name: CI - Moodify React

on:
  push:
    branches: [feature]
  pull_request:
    branches: [feature]

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Instalar dependências
        run: npm install
  
  build:
    needs: setup
    runs-on: ubuntu-latest

    steps:
      - name: Build do projeto
        run: npm run build

      - name: Verificar se a build foi gerada com sucesso
        run: ls -l dist
      
      - name: Mensagem de sucesso
        run: echo "Build concluída com sucesso!"
